export const amenitiesUnit = [
    { name: "Lavanderia", value: "unitLaundry" },
    { name: "Varanda", value: "balcony" },
    { name: "Varanda Gourmet", value: "gourmetBalcony" },
    { name: "Piscina", value: "unitPool" },
    { name: "Banheira", value: "bathtub" },
    { name: "Chuveiro a gás", value: "gasShower" },
    { name: "Chuveiro elétrico", value: "electricShower" },
    { name: "Box de vidro", value: "glassBox" },
    { name: "Fechadura eletrônica", value: "electronicLock" },
    { name: "Quarto de serviço", value: "maidBedroom" },
    { name: "Banheiro de serviço", value: "maidBathroom" },
    { name: "Ventilador de teto", value: "ceilingFan" },
    { name: "Cozinha americana", value: "kitchenCountertop" },
    { name: "Cortina blackout", value: "blackoutCurtain" },
    { name: "Cortina antirruído", value: "noiseReductionCurtain" },
    { name: "Mobiliado", value: "furnished" },
    { name: "Máquina de lavar", value: "washer" },
    { name: "Lavadoura de louças", value: "dishwasher" },
    { name: "Ar-condicionado", value: "airConditioning" },
    { name: "Armário de cozinha", value: "kitchenCabinet" },
    { name: "Armário de banheiro", value: "bathroomCabinet" },
    { name: "Guarda-roupa", value: "wardrobe" },
    { name: "Closet", value: "closet" },
    { name: "Cama de solteiro", value: "singleBed" },
    { name: "Cama de casal", value: "doubleBed" },
    { name: "Espelho no banheiro", value: "bathroomMirror" },
    { name: "Mesa", value: "table" },
    { name: "Sofá", value: "couch" },
    { name: "Televisão", value: "tv" },
    { name: "Utensílios de cozinha", value: "kitchenTools" },
    { name: "Fogão", value: "stove" },
    { name: "Cooktop", value: "cooktop" },
    { name: "Geladeira", value: "fridge" },
    { name: "Microondas", value: "microwave" },
]